name = "grafana-discord-worker"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[vars]
# Set TOKEN to a random string - this will be used to authenticate requests to the worker

[observability.logs]
enabled = true
